import astropy.units as u
import hashlib
import os
import numpy as np
import warnings
from astropy.time import Time
from scipy.interpolate import interp1d
from pathlib import Path
from orbit_gen import Family, Orbit, RunConfig
from orbit_gen.setup.config import ContinuationConfig
from orbit_gen.setup.system_config import SystemConfig, EM_SYSTEM, SE_SYSTEM
from orbit_gen.setup.orbit_ic import OrbitIC
from orbit_gen.setup.presets import PRESETS
from orbit_gen.setup.kernels import ensure_kernels
from orbit_gen.utils import units

from EXOSIMS.Prototypes.Observatory import Observatory

_SYSTEMS = {"EM": EM_SYSTEM, "SE": SE_SYSTEM}


class ObservatoryCR3BP(Observatory):
    """Observatory on a CR3BP periodic orbit, generated via ``orbit-gen``.

    The ``orbit`` method from the Observatory prototype is overloaded to
    implement a space telescope on a periodic orbit (e.g. halo, Lyapunov)
    generated by ``orbit-gen``.

    Args:
        system (str):
            CR3BP system used, ``"SE"`` for Sun-Earth, ``"EM"`` for
            Earth-Moon. Defaults to ``"SE"``.
        preset (str):
            Name of a preset in :py:data:`orbit_gen.setup.presets.PRESETS`
            used as the initial condition for continuation. Defaults to
            ``"SE_L2_Northern_Halo"``.
        desired_period (float, optional):
            Desired orbital period in days. Used to determine which generated
            orbit is used for the observatory. A value of None will cause the
            last orbit generated to be selected. Defaults to None.
        eps (float):
            Convergence tolerance on the constraint residual norm.
            Defaults to 1e-6.
        max_iter (int):
            Maximum number of Newton iterations for a single differential
            correction attempt. Defaults to 1000.
        max_period_days (float):
            Maximum allowable full orbit period, in days. Defaults to 500.0.
        max_solutions (int):
            Maximum number of converged periodic orbits to generate before
            terminating continuation. Defaults to 20.
        step (float):
            Pseudo-arclength continuation step size in canonical units.
            Defaults to 0.01.
        orbit_epoch (float):
            ***************************************************FILL IN
        **specs:
            :ref:`sec:inputspec`

    Attributes:
        canonical_units (orbit_gen.setup.system_config.CanonicalUnits):
            Canonical length/time scales for the orbit's system.
        orbit_epoch (float):
            ***************************************************FILL IN
        orbit_period_days (astropy.units.Quantity):
            Orbit period in days.
        observatory_orbit (orbit_gen.orbit.Orbit):
            The single orbit (from ``family.orbits[orbit_index]``) this
            Observatory sits on.
        primary_name (str):
            Name of the primary body in the CR3BP.
        secondary_name (str):
            Name of the secondary body in the CR3BP.
        r_interp (scipy.interpolate.interp1d):
            Interpolant for synodic-frame position, evaluated at canonical
            time, returning canonical-unit position.
        v_interp (scipy.interpolate.interp1d):
            Interpolant for synodic-frame velocity, same units convention
            as r_interp. Optional -- only needed if velocity is used
            downstream (e.g. dV calculations).

    .. note::

        All CR3BP-frame quantities (position, velocity, time) are stored and
        interpolated in canonical units. Conversion to physical units (AU,
        days) happens only at the boundary, inside ``orbit()``.

    """

    def __init__(
        self,
        system="SE",
        preset="SE_L2_Northern_Halo",
        desired_period=None,
        eps=1e-6,
        max_iter=1000,
        max_period_days=500.0,
        max_solutions=20,
        step=0.01,
        orbit_epoch=None,
        **specs,
    ):
        # run prototype constructor first
        Observatory.__init__(self, **specs)

        assert (
            system in _SYSTEMS
        ), f"Unknown system {system!r}; must be one of {list(_SYSTEMS)}."
        assert (
            preset in PRESETS
        ), f"Unknown preset {preset!r}; must be one of {list(PRESETS)}."
        assert system == "SE", "Earth-Moon system not currently supported"

        if system == "SE":
            self.primary_name = "Sun"
            self.secondary_name = "Earth"
        elif system == "EM":
            self.primary_name = "Earth"
            self.secondary_name = "Moon"

        cache_string = (
            f"system={system}"
            f"|preset={preset}"
            f"|eps={eps}"
            f"|max_iter={max_iter}"
            f"|max_period_days={max_period_days}"
            f"|max_solutions={max_solutions}"
            f"|step={step}"
        )

        cache_hash = hashlib.md5(cache_string.encode("utf-8")).hexdigest()
        cache_dir = Path(self.cachedir) / f"orbit_gen_{cache_hash}"

        sys = _SYSTEMS[system]
        ic = PRESETS[preset]

        continuation = ContinuationConfig(
            max_iter=max_iter,
            eps=eps,
            step=step,
            max_solutions=max_solutions,
            max_period_days=max_period_days,
        )

        cfg = RunConfig(
            system=sys,
            ic=ic,
            continuation=continuation,
            output_dir=cache_dir,
            show_plots=False,
        )

        cache_path = os.path.join(cache_dir, cfg.output_filename)

        if os.path.exists(cache_path):
            # Load cached data
            with np.load(cfg.output_path) as data:
                states = data["states"]
                periods = data["periods"]
                mu_star = data["mu_star"]

            # Set up system constants using spice
            family = Family.__new__(Family)
            family.cfg = cfg
            family.orbits = []
            family._setup_constants()

            if desired_period is not None:
                idx = self._select_orbit_by_period(
                    periods, desired_period, family.cfg.system.canonical_units
                )
            else:
                idx = -1

            state = states[idx]
            period = periods[idx]

            self.observatory_orbit = Orbit(
                x0=state[0],
                z0=state[2],
                vy0=state[4],
                period=period,
                mu_star=mu_star,
                canonical_units=family.cfg.system.canonical_units,
            )

            self.observatory_orbit.propagate()

        else:
            family = Family(cfg)
            family.save()

            periods = np.array([orbit.period for orbit in family.orbits])

            if desired_period is not None:
                idx = self._select_orbit_by_period(
                    periods, desired_period, family.cfg.system.canonical_units
                )
            else:
                idx = -1

            self.observatory_orbit = family.orbits[idx]

        self.canonical_units = self.observatory_orbit.canonical_units

        self.orbit_period_days = units.time_to_dimensional(
            self.observatory_orbit.period, self.canonical_units
        )

        self.r_interp = interp1d(
            self.observatory_orbit.times,
            self.observatory_orbit.states[:, 0:3].T,
            kind="cubic",
            assume_sorted=True,
        )
        self.v_interp = interp1d(
            self.observatory_orbit.times,
            self.observatory_orbit.states[:, 3:6].T,
            kind="cubic",
            assume_sorted=True,
        )

        if orbit_epoch is None:
            orbit_epoch = 0.0
        self.orbit_epoch = Time(
            np.array(orbit_epoch, ndmin=1, dtype=float), format="mjd", scale="tai"
        )

    def _select_orbit_by_period(self, periods, desired_period, canonical_units):
        target = units.time_to_canonical(desired_period * u.d, canonical_units)
        idx = np.argmin(np.abs(periods - target))
        closest_period = units.time_to_dimensional(
            periods[idx], canonical_units
        ).to_value(u.day)
        if np.abs(closest_period - desired_period) > 0.1 * desired_period:
            warnings.warn(
                f"Desired orbit period is {desired_period} days and the "
                f"closest generated orbit period is {closest_period} days. "
                "Please adjust continuation parameters if a more precise "
                "period is desired."
            )
        return idx

    def orbit(self, currentTime, eclip=False):
        """Finds observatory orbit positions vector in heliocentric equatorial
        (default) or ecliptic frame for current time (MJD).

        This method returns the telescope's position on its CR3BP orbit, as
        generated by ``orbit-gen``.

        Args:
            currentTime (~astropy.time.Time):
                Current absolute mission time in MJD
            eclip (bool):
                Boolean used to switch to heliocentric ecliptic frame.
                Defaults to False, corresponding to heliocentric equatorial
                frame.

        Returns:
            ~astropy.units.Quantity(~numpy.ndarray(float)):
                Observatory orbit positions vector in AU.
        """

        mjdtime = np.array(currentTime.mjd, ndmin=1)
        dt_days = mjdtime - self.orbit_epoch.to_value("mjd")
        t_canonical = units.time_to_canonical(dt_days * u.d, self.canonical_units)
        t_canonical = t_canonical % self.observatory_orbit.period

        r_synodic = self.r_interp(t_canonical).T

        r_primary = self.solarSystem_body_position(
            currentTime, self.primary_name, eclip=True
        )
        r_secondary = self.solarSystem_body_position(
            currentTime, self.secondary_name, eclip=True
        )

        sep = (r_secondary - r_primary).to_value(u.AU)
        theta = np.arctan2(sep[:, 1], sep[:, 0])

        r_inertial = np.array(
            [self.rot(-theta[x], 3) @ r_synodic[x, :] for x in range(currentTime.size)]
        )
        r_inertial_au = units.pos_to_dimensional(r_inertial, self.canonical_units).to(
            u.AU
        )

        r_bary = r_primary + self.observatory_orbit.mu_star * (r_secondary - r_primary)

        r_obs = r_bary + r_inertial_au

        assert np.all(
            np.isfinite(r_obs)
        ), "Observatory positions vector r_obs has infinite value."

        if not eclip:
            r_obs = self.eclip2equat(r_obs, currentTime)

        return r_obs
