from EXOSIMS.Observatory.WFIRSTObservatory import WFIRSTObservatory
import astropy.units as u
from astropy.time import Time
from astropy.coordinates import SkyCoord
import numpy as np
import os, inspect
import scipy.interpolate as interpolate
try:
    import cPickle as pickle
except:
    import pickle

class WFIRSTObservatoryL2(WFIRSTObservatory):
    """ WFIRST Observatory at L2 implementation. 
    Only difference between this and the WFIRSTObservatory implementation
    is the orbit method, and carrying an internal missionStartTime value,
    which should be the same as the one in TimeKeeping (necessary due to 
    orbit method interface, which calls for absolute time).

    Orbit is stored in pickled dictionary on disk (generated by MATLAB
    code adapted from E. Kolemen (2008).  Describes approx. 6 month halo
    which is then patched for the entire mission duration).
    """

    def __init__(self, missionStart=60634., orbit_datapath=None, **specs):
        
        # Run prototype constructor __init__ 
        WFIRSTObservatory.__init__(self,**specs)
        
        # Set own missionStart value
        self.missionStart = Time(float(missionStart), format='mjd', scale='tai')
        
        # Find and load halo orbit data
        # data is in heliocentric ecliptic coords
        # time is 2\pi = 1 sideral year
        
        if orbit_datapath is None:
            classpath = os.path.split(inspect.getfile(self.__class__))[0]
            filename = 'L2_halo_orbit_six_month_v3.p'
            orbit_datapath = os.path.join(classpath, filename)
        if not os.path.exists(orbit_datapath):
            raise Exception("Orbit data file not found.")
        halo = pickle.load( open( orbit_datapath, "rb" ) )
        
        # unpack orbit properties
        self.orbit_period = halo['te'].flatten()[0]/(2*np.pi)*u.year
        self.L2_dist = halo['x_lpoint'][0][0]*u.AU
        self.orbit_pos = halo['state'][:,0:3]*u.AU #this is in rotating frame wrt the sun
        self.orbit_vel = halo['state'][:,3:6]*u.AU/u.year*(2*np.pi) #velocity in rotating frame
        self.orbit_pos[:,0] -= self.L2_dist #now with respect to L2, still in rotating frame
        self.orbit_time = halo['t'].flatten()/(2*np.pi)*u.year
        # create interpolant (years & AU units)
        self.orbit_interp = interpolate.interp1d(self.orbit_time.value,\
                self.orbit_pos.value.T,kind='cubic')
        # create interpolant for orbital velocity (years & AU/yr units)
        self.orbit_V_interp = interpolate.interp1d(self.orbit_time.value,\
                self.orbit_vel.value.T,kind='cubic')

    def orbit(self, currentTime):
        """Finds observatory orbit position vector in heliocentric equatorial frame.
        
        This method returns the WFIRST L2 Halo orbit position vector
        in the heliocentric equatorial frame.
        
        Args:
            currentTime (astropy Time array):
                Current absolute mission time in MJD
        
        Returns:
            r_sc (astropy Quantity nx3 array):
                Observatory (spacecraft) position vector in units of km
        
        """
        
        # reshape currentTime
        currentTime = currentTime.reshape(currentTime.size)
        
        # find time from Earth equinox and interpolated position
        equinox = Time(60575.25,format='mjd')
        deltime = (currentTime - equinox).to('year')
        
        # calculating Earth position
        r_Earth = self.solarSystem_body_position(currentTime, 'Earth')
        dist_Earth = SkyCoord(r_Earth[:,0],r_Earth[:,1],r_Earth[:,2],representation='cartesian').heliocentrictrueecliptic.icrs.distance
        
        # weighting L2 position with Earth-Sun distance
        L2_corr_dist = np.ones(currentTime.size)*self.L2_dist * dist_Earth.to('AU').value
#         # alternatively, just add the Earth distance fluctuation
#         L2_corr_dist = np.ones(currentTime.size)*self.L2_dist + (dist_Earth - 1*u.AU).to('AU')
        
        # add L2 position to get current ecliptic coord
        th = np.mod(deltime.value,1.)*2*np.pi
        cpos = self.orbit_interp(np.mod(deltime,self.orbit_period).value)
        cpos += np.array([np.cos(th),np.sin(th),np.zeros(th.size)])*L2_corr_dist.to('AU').value
        cpos = cpos.T
        
        # finally, rotate into equatorial plane
        obe = self.obe(self.cent(currentTime))
        
        # if single currentTime value
        if type(obe) == float:
            r_sc = (np.dot(self.rot(np.radians(-obe),1),cpos)*u.AU).to('km')
        # else if several currentTime values
        else:
            r_sc = np.empty((obe.size, 3))*u.km
            for i in range(obe.size):
                r_sc[i] = (np.dot(self.rot(np.radians(-obe[i]),1),cpos[i])*u.AU).to('km')
      
        assert np.all(np.isfinite(r_sc)), 'Observatory position vector r_sc has infinite value.'
        
        return r_sc.to('km').reshape(currentTime.size,3)
